name: Test and Deploy

on:
    push:
        branches:
            - main
            - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - run: |
        flutter build ios --no-codesign
        cd build/ios/iphoneos
        mkdir Payload
        cd Payload
        ln -s ../Runner.app
        cd ..
        zip -r app.ipa Payload

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.0
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: true


    
