name: CI Tests

on:
    push:
        branches:
            - main
            - master

jobs:
  # This workflow contains a single job called "build"
  build:
    name: flutter build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11"
      FLUTTER_VERSION: "2.5.3"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.5.3"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test